merged changes from master and add tests for secondary sitetype
officiallygod/bluehost-wordpress-plugin pull request #9
Opened 2022-08-26 10:47 UTC by abhijitb

2022-08-29 13:33 UTC, arunshenoy99 approved these changes
We can loop through all the categories using `each` in future iterations.

2022-08-31 17:13 UTC, arunshenoy99 requested changes
One comment to reduce the time, rest all seem to be fine to me, if you have time we can modify the code to loop through all the boxes as well (Ref products.cy.js) but that is optional.

2022-08-31 17:13 UTC, arunshenoy99 commented on tests/cypress/integration/newfold-labs/wp-module-onboarding/steps/sitetype-secondary.cy.js
> +        cy.wait(5000);
Can we reduce this wait time to maybe `2000-3000`?

2022-09-01 12:51 UTC, arunshenoy99 approved these changes
Looks good thanks AB.

2022-09-01 13:32 UTC, officiallygod approved these changes

2022-09-01 13:33 UTC, merged